steps:
#- task: CacheBeta@0
#  displayName: SUNDIALS cache
#  inputs:
#    key: SUNDIALS | "$(Agent.OS)" | "${{ parameters.vmImage }}" | "$(SUNDIALS_VERSION)"
#    path: $(HOME)/sundials/
#  condition: and(succeeded(), ne(variables['SUNDIALS_VERSION'], ''))

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'
  condition: and(succeeded(), ne(variables['python.version'], 'Pre'))

- script: |
    ci/ensure_sundials_installed.sh
    python -m pip install --upgrade pip
    pip install tox codecov setuptools wheel
  displayName: 'Install pip dependencies'

- script: env
  displayName: 'print env'

- script: |
    tox
  displayName: 'tox'
  # env: {"BASH_ENV": "./ci/ensure_sundials_installed.sh"}

- script: |
    codecov
  displayName: 'codecov'
- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Upload to codecov.io'